"""Create initial tables

Revision ID: 3e1a43912dfe
Revises:
Create Date: 2025-08-10 17:23:16.815501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e1a43912dfe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('nationality', sa.String(length=255), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('marriage_date', sa.Date(), nullable=True),
    sa.Column('career_ambition', sa.Text(), nullable=True),
    sa.Column('significant_achievements', sa.Text(), nullable=True),
    sa.Column('professional_failures', sa.Text(), nullable=True),
    sa.Column('strengths', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('weaknesses', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('referred_by_employee', sa.Boolean(), nullable=True),
    sa.Column('referrer_name', sa.String(length=255), nullable=True),
    sa.Column('referrer_contact_no', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    op.create_table('employee_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('pin_code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('mobile_phone_no', sa.String(length=20), nullable=True),
    sa.Column('email_id', sa.String(length=255), nullable=True),
    sa.Column('telephone_no', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_contacts_email_id'), 'employee_contacts', ['email_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_contacts_email_id'), table_name='employee_contacts')
    op.drop_table('employee_contacts')
    op.drop_table('employee_addresses')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
